server:
  port: 8081

logging:
  config: classpath:log4j2.xml


#logging:
#  level:
#    root: info
#  pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'


# 日志输出格式：
#   %d表示日期时间，
#   %thread表示线程名，
#   %-5level：级别从左显示5个字符宽度
#   %logger{50} 表示logger名字最长50个字符，否则按照句点分割。
#   %msg：日志消息，
#   %n是换行符
#
#   %d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n
#   %clr(){blue}进行颜色修改